version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ${SERVER_DOCKERFILE}
    image: ${DOCKER_USERNAME}/${DOCKER_BACKEND_REPOSITORY}:${RUN_ID}
    restart: always
    container_name: backend
    command: bash -c "
      cd /app/src
      && python -m alembic upgrade head
      && cd /
      && python3 /app/src/app.py"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - server:${DATA_FOLDER_PATH}
  redis-server:
    image: redis/redis-stack-server
    restart: always
    container_name: redis-server
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - redis-server:${DATA_FOLDER_PATH}
  rq-worker:
    image: ${DOCKER_USERNAME}/${DOCKER_BACKEND_REPOSITORY}:${RUN_ID}
    restart: always
    container_name: rq-worker
    command: rq worker --path /app/src --url redis://:${REDIS_PASSWORD}@${REDIS_HOST}:6379 mapping_nomenclatures sync_nomenclatures retrain_classifier classification documents
    env_file:
      - .env
    volumes:
      - server:${DATA_FOLDER_PATH}
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - datastep-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<your_strong_password>
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
  dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    container_name: dbeaver
    volumes:
      - datastep-dbeaver:/opt/cloudbeaver/workspace
    ports:
      - "8978:8978"
  chroma-db:
    image: chromadb/chroma
    restart: always
    container_name: chroma-db
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8001:8000"
volumes:
  server:
  redis-server:
  mssql:
  datastep-db:
  datastep-dbeaver:
  chroma-data:
    driver: local

