version: "3"

services:

  server:
    image: ${CONTAINER_IMAGE}:${CI_PIPELINE_ID}
    command: bash -c "
      cd /app/src
      && python -m alembic upgrade head
      && cd /
      && python3 /app/src/app.py"
    ports:
      - "8080:8080"
    env_file:
      - .env.run
    volumes:
      - "/home/wv-bleschunovd/data:/app/data"
  rq-worker:
    image: ${CONTAINER_IMAGE}:${CI_PIPELINE_ID}
    command: rq worker --path /app/src --url redis://${REDIS_HOST}:6379 mapping_nomenclatures sync_nomenclatures retrain_classifier classification
    env_file:
      - .env.run
    volumes:
      - "/home/wv-bleschunovd/data:/app/data"
  chroma-db:
    image: chromadb/chroma
    container_name: chroma-db
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8001:8000"
volumes:
  chroma-data:
    driver: local

